cUsers/urls.py
from django.urls import path, include
from .views import RecruiterSignUpView, ApplicantSignUpView, SecretarySignUpView, SupervisorSignUpView

app_name = 'accounts'
urlpatterns = [
    # path('accounts/', include('django.contrib.auth.urls')),
    path('signup/recruiter/', RecruiterSignUpView.as_view(), name='recruiter_signup'),
    path('signup/applicant/', ApplicantSignUpView.as_view(), name='applicant_signup'),
    path('signup/secretary/', SecretarySignUpView.as_view(), name='secretary_signup'),
    path('signup/supervisor/', SupervisorSignUpView.as_view(), name='supervisor_signup'),
]

# (1, 'Employer'),
# (2, 'Employee'),
# (3, 'secretary'),
# (4, 'supervisor'),
# (5, 'admin'),

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    # path('accounts/', include('accounts.urls')),
    path('accounts/', include('cUsers.urls')),

    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# if settings.DEBUG:
#     # This allows the error pages to be debugged during development, just visit
#     # these url in browser to see how these error pages look like.
#     urlpatterns += [
#         path(
#             "400/",
#             default_views.bad_request,
#             kwargs={"exception": Exception("Bad Request!")},
#         ),
#         path(
#             "403/",
#             default_views.permission_denied,
#             kwargs={"exception": Exception("Permission Denied")},
#         ),
#         path(
#             "404/",
#             default_views.page_not_found,
#             kwargs={"exception": Exception("Page not Found")},
#         ),
#         path("500/", default_views.server_error),
#     ]
#     if "debug_toolbar" in settings.INSTALLED_APPS:
#         import debug_toolbar
#
#         urlpatterns = [
#                           path("__debug__/", include(debug_toolbar.urls))
#                       ] + urlpatterns

home/urls.py
from django.urls import path, include
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.

class HomePageView(TemplateView):
    template_name = 'home.html'

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<main>
    {% block content %}
    {% endblock content %}
</main>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}multi user App | Home{% endblock title %}

{% block content %}
    {% if user.is_authenticated %}
        Hi {{ user.username }}! You are {{ user.age }} years old.
        <p><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">Log In</a> |
        <br><br>
        <a href="{% url 'accounts:recruiter_signup' %}">Recruiter Sign Up</a> |
        <br><br>
        <a href="{% url 'accounts:applicant_signup' %}">Applicant Sign Up</a> |
        <br> <br>
        <a href="{% url 'accounts:secretary_signup' %}">Secretary Sign Up</a> |
        <br><br>
        <a href="{% url 'accounts:supervisor_signup' %}">Supervisor Sign Up</a> |
    {% endif %}
{% endblock content %}